name: Auto Translate

on:
  push:
    branches:
      - 'feature/auto-translate'
    paths:
      - 'docs/app-router/**'

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      # feature/auto-translateへcheckout
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: feature/auto-translate

      # ファイル取得、翻訳、ファイル上書き処理
      - name: check and get changed files
        run: sh auto_translate/script/check_change.sh "${{ secrets.GITHUB_TOKEN }}"
      # - name: translation with chatGPT
      #   run: sh auto_translate/script/translate.sh
      # - name: Overwrite translation results
      #   run: sh auto_translate/script/over_write.sh
      
      # # ブランチのコミット
      # - name: Add and Commit
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     branch: fix/hoge_${{ env.CURRENT_DATETIME }}
      #     message: ${{ env.PR_TITLE }}
      #     add: ${{ env.JSON_FILE_PATH }}
      
      # # pull requestの作成
      # - name: Create pull request
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     source_branch: fix/hoge_${{ env.CURRENT_DATETIME }}
      #     destination_branch: ${{ env.DEST_BRANCH }}
      #     pr_title: ${{ env.PR_TITLE }}
      #     pr_template: ${{ env.PR_TEMPLATE }}
      #     pr_label: ${{ env.PR_LABEL }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}