name: Auto Translate

on:
  push:
    branches:
      - 'feature/auto-translate'
    paths:
      - 'docs/app-router/**'

permissions:
  contents: write
jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      # feature/auto-translateへcheckout
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: feature/auto-translate

      # ファイル取得、翻訳、ファイル上書き処理
      - name: check and get changed files
        run: bash auto_translate/script/check_change.sh "${{ secrets.GITHUB_TOKEN }}"
      - name: translation with chatGPT
        run: bash auto_translate/script/translate.sh

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add changes to Git
        run: |
          git add .

      - name: Commit changes
        run: |
          git commit -m "Automated commit from GitHub Actions"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:${{ github.ref }}